### PR TITLE
Version 3

### PR DESCRIPTION
**Pull request by Abrar052**
###Microverse Portfolio Project (Mobile version)
-Updated index.html by Adding the Next Two Sections, and aligning the List of Languages, Frameworks, and Skills. Added Icons to the headings of the list.
-Updated style.css by Adding Style to New Two Sections, the List of Languages, Frameworks, and Skills, and Icons to the headings of the list.
-Updated JSON Packages
-Updated .gitignore
-Added Images to the New Sections

### CODE REVIEW

**Review by victorokoroji — CHANGES_REQUESTED** [review]
Hi @Abrar052,

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️

- [ ] Kindly make sure that git properly ignores node modules as the previous reviewer suggested. Currently, all files from node modules are pushed to git. 
You can run this command to remove the node modules
```
git rm -r --cached .
git add .
git commit -m "remove gitignore files"
git push
```
_Check the comments under the review._

## Optional suggestions
- Kindly make sure that you don't open a new pull request when changes are required. You should push your changes to the same pull request.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Abrar052** [comment]
@vickymarz i applied the commands you just sent but they didn't work

**Comment by Abrar052** [comment]
how can I make sure the gitignore ignores the node_module file. I just have to make this one change my whole project is clear otherwise I think I had to make a new repository and work on it without installing the node_module directory.

**Comment by victorokoroji** [comment]
Can you screenshot what you are getting on your console after running the code

**Comment by victorokoroji** [comment]
Run this one 

git rm -r --cached node_modules

**Comment by Abrar052** [comment]
[image: CMDER-1.png][image: CMDER-2.png][image: CMDER-3.png]

**Comment by Abrar052** [comment]
in the first commands, it says already up to date and the second one you
just send me by email says fatal: pathspec 'node_modules' did not match any
files

**Comment by Abrar052** [comment]
@vickymarz sorry I replied to you and was waiting for your answer but I forgot to mention your name. in the first commands, it says already up to date, and in the second one you just send me by email says fatal: pathspec 'node_modules' did not match any
file
CMDER-1
CMDER-2
CMDER-3
s

**Comment by victorokoroji** [comment]
Try to add something to your code and then push

**Comment by victorokoroji** [comment]
I think the node_modules has been removed

**Comment by Abrar052** [comment]
@vickymarz I made changes in the code and push it. i don't know how to confirm if node_module is ignore or not can you plz take a look and tell me for sure if node_module is removed or not. i want to make sure before I request a review.

**Comment by victorokoroji** [comment]
@Abrar052  when you are free, we can meet on zoom to fix it

**Comment by Abrar052** [comment]
@vickymarz We can do it right now it is break time and it is the best time for it

**Comment by victorokoroji** [comment]
Please call me on zoom. I am okoroji Victor ebube

**Review by victorokoroji — CHANGES_REQUESTED** [review]
Hi @Abrar052  

You have worked so hard to implement some of the requested changes, but there are still some which aren't addressed yet.

- I understand that the issue of removing the node_modules from the repo has lingered for  long. I will recommend you use this [FAQ](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-) to schedule a 1:1 meeting with a senior code reviewer and I believe you will get answers. See this process as a learning opportunity for you. Weldone 👍 



## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
